export const sample1 = (annotations: [string, string, string, string]) =>
    `Except for an abortive royal colony established under Major Claus Paarss between 1728 and 1730, colonial Greenland was administered by companies under royal charter until 1908. Hans Egede's Hope Colony was organized under the auspices of the Bergen Greenland Company prior to its bankruptcy in 1727; it was succeeded by the merchant Jacob Severin (1733–1749), the General Trade Company (Det almindelige Handelskompagni; 1749–1774), and finally the Royal Greenland Trading Department (KGH; 1776–1908).

${annotations[0]}
Early hopes of mineral or agricultural wealth were dashed, and open trade proved a failure owing to other nations' better quality, lower priced goods and hostility. Kale, lettuce, and other vegetables were successfully introduced, but repeated attempts to cultivate wheat or clover failed throughout Greenland, limiting the ability to raise European livestock. After government-funded whaling failed, the KGH eventually settled on maintaining the native Greenlanders in their traditional pursuits of hunting and whaling and enforced a monopoly on trade between them and Europe. Repeated attempts to open trade were opposed on both commercial and humanitarian grounds, although minor reforms in the 1850s and 60s lowered the prices charged to the natives for "luxuries" like sugar and coffee; transferred more of the KGH's profits to local communities; and granted the important Ivigtut cryolite concession to a separate company.

During the years before World War I, the KGH's independence was curtailed and the company folded into the Ministry of the Interior. Climate change, apparent since the 1920s, disrupted traditional Kalaallit life as the milder weather reduced the island's seal populations but filled the waters offshore with cod. After World War II, reforms were finally enacted by the Danish Greenland Commission composed of Greenland Provincial Council members and Danish economists. The report outlined a program to end the KGH model and establish a modern welfare state on the Danish model and supported by the Kingdom Government. The KGH monopolies were ended in 1950; Greenland was made an equal part of the Kingdom of Denmark in 1953 and Home Rule granted in 1979.

${annotations[1]}
The KGH had long opposed urbanization of the Kalaallit Greenlanders, but during the 1950s and 1960s the Danish government introduced an urbanization and modernization program aimed at consolidating existing settlements. The program was intended to reduce costs, improve access to education and health care, and provide workers for modernized cod fisheries, which were growing rapidly at the time. The program faced a number of problems including the collapse of the fisheries and the shoddy construction of many of the buildings, particularly the infamous Blok P, and produced a number of problems of its own, including continuing unemployment and alcoholism.

${annotations[2]}
Greenland left the European Economic Community in February 1985, principally due to EEC policies on fishing and sealskin. Most EU laws do not apply to Greenland; however, owing to its connection with Denmark, Greenland continues to enjoy preferential access to EU markets. In the same year, Greenland exercised its new control over the Royal Greenland Trading Company to reestablish it as KNI. Over the next few decades, divisions of the conglomerate were slowly spun off and competition within the Greenlandic economy somewhat increased.

${annotations[3]}
Following the closure of the Maarmorilik lead and zinc mine in 1990 and the collapse of the cod fisheries amid colder ocean currents, Greenland faced foreign trade deficits and a shrinking economy, but it has been growing since 1993.`;
